name: Build

on:
  push:
    branches: [master, production-namebase]
  pull_request:
    branches: [master, production-namebase]


jobs:
  lint:
    name: Lint & Doc
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install --location=global bslint @hns-dev/bsdoc

    - name: Lint
      run: npm run lint

    - name: Docs
      run: npm run build-docs

  build-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            node-version: 12.x
          - os: ubuntu-20.04
            node-version: 14.x
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 18.x

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install libunbound
      run: |
        sudo apt-get update
        sudo apt-get install -y libunbound-dev

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test
